apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  postgres-db: tech_challenge
  postgres-user: postgres
  postgres-password: postgres
  postgres-host: database-svc
  database-url: postgresql://postgres:postgres@database-svc/tech_challenge?schema=public
